import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Order {

    //write order to database and share with other microservices

    UUID uuid;   //stored in db as varchar(36)
    List<Integer> itemIdList = new ArrayList<>();
    List<Integer> itemFreqencyList = new ArrayList<>();



    /////////////////////////On Runtime\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    int orderStatus; //return   0 - new     1 - completed   5 - processing





    /////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    OrderProbabilityGenerator orderGenerator = new OrderProbabilityGenerator();

    //////////////////Constructor-- only construct Orders Object if Order is generated by Ordergenerator\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    public Order(){
        orderGenerator.generateRandomOrders();
        if( !(orderGenerator.itemIdList.isEmpty()) ){
            //generate orderID
            //add items to lists
            this.uuid = UUID.randomUUID();
            this.itemIdList = orderGenerator.itemIdList;
            this.itemFreqencyList = orderGenerator.itemFrequencyList;
            this.orderStatus = 0;

            OrderList.orderUUIDList.add(this.uuid);

        }

    }

    /////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    //Status must be updated at runtime
    public void setOrderStatus(int status){

        this.orderStatus = status;
    }

    public String getOrderStatus(){

        if(orderStatus == 0){
            return "NEW";
        }
        else if (orderStatus == 1){
            return "COMPLETED";
        }

        return "PROCESSING";
    }

    //////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

}