import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Order {

    //write order to database

    UUID uuid;   //stored in db as varchar(36)
    List<Integer> itemList = new ArrayList<>();
    List<Integer> itemFrqencyList = new ArrayList<>();

    OrderGenerator orderGenerator = new OrderGenerator();

    //////////////////Constructor-- only construct Orders Object if Order is generated by Ordergenerator\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    public Order(){
        orderGenerator.generateRandomOrders();
        if( !(orderGenerator.itemIdList.isEmpty()) ){
            //generate orderID
            //add items to lists
            this.uuid = UUID.randomUUID();
            this.itemList = orderGenerator.itemIdList;
            this.itemFrqencyList = orderGenerator.itemFrequencyList;

        }

    }

}