import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Order {

    //write order to database

    UUID uuid;   //stored in db as varchar(36)
    List<Integer> itemList = new ArrayList<>();
    List<Integer> itemFrqencyList = new ArrayList<>();

    OrderProbabilityGenerator orderProbabilityGenerator = new OrderProbabilityGenerator();

    //////////////////Constructor-- only construct Orders Object if Order is generated by OrderProbabilityGenerator\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    public Order(){
        orderProbabilityGenerator.generateRandomOrders();
        if( !(orderProbabilityGenerator.itemIdList.isEmpty()) ){
            //generate orderID
            //add items to lists
            this.uuid = UUID.randomUUID();
            this.itemList = orderProbabilityGenerator.itemIdList;
            this.itemFrqencyList = orderProbabilityGenerator.itemFrequencyList;

        }

    }

}